name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake
    
    - name: Create build directory
      run: mkdir build && cd build
      
    - name: Configure CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
      working-directory: ${{github.workspace}}/build
      
    - name: Build
      run: cmake --build .
      working-directory: ${{github.workspace}}/build
