# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MTSD_LW_1-2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: MTDS_LW_1-2/MTDS_LW_1-2.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  #TEST_PROJECT_PATH: MTDS_LW_1-2/MTDS_test/MTDS_test.vcxproj
  TEST_EXECUTABLE_PATH: MTDS_LW_1-2/x64/Release/MTDS_test.exe

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Run the test executable and check for failures
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: |
        output=$(./MTDS_LW_1-2/x64/Release/MTDS_test.exe)
        echo "$output"
        if echo "$output" | grep -q "\[  FAILED  \]"; then
          echo "One or more tests failed."
          exit 1
        fi




